apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tp02-mychart-nginx.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tp02-mychart-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tp02-mychart-nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
         volumeMounts:
          - name: config
            mountPath: "/usr/share/nginx/html"
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: contenu-html
          # An array of keys from the ConfigMap to create as files
          items:
          - key: "index.html"
            path: "index.html"


          