apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
spec:
  containers:
  - name: my-nginx
    image: nginx:latest
    volumeMounts:
    - name: code-html
      mountPath: /usr/share/nginx/html/index.html
  volumes:
  - name: code-html
    configMap:
      name: contenu-html